# Check https://circleci.com/docs/2.0/language-python/ for more details

build-venv: &build-venv
  name: create virtual env and install dependencies
  command: |
    python -m venv venv
    . venv/bin/activate
    pip install -r requirements.txt

run-test: &run-test
  name: run test cases
  command: |
    . venv/bin/activate
    pytest tests/mdx_link2md_test.py

version: 2
jobs:
  run-tests-37-j:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: *build-venv

      - save_cache:
          paths:
          - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run: *run-test

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2

  run-tests-37:
    jobs:
      - run-tests-37-j
